---
version: "3"
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=4443
      - DOCKER_HUB_USERNAME=USER #optional
      - DOCKER_HUB_PASSWORD=PASS #optional
      - DOCKER_MTU=1500 #optional
    volumes:
      - ./kasm/data:/opt
      - ./kasm/profiles:/profiles #optional
      - /dev/input:/dev/input #optional
      - /run/udev/data:/run/udev/data #optional
    ports:
      - 3000:3000
      - 4443:4443
    restart: unless-stopped
  networks:
    kasm_network:
      aliases:
        - kasm
networks:
  kasm_network:
    name: proxy_swag_network
      external: true
    
